version: '2'
services:
  web:
    build: ./
    ports:
      - "81:80"
    volumes:
      - "../:/var/www/html/"
      # - "./data/:/var/log/"
      # - "./etc/php:/etc/php/7.1/apache2"
      # - "./etc/apache2:/etc/apache2/sites-available"
    container_name: kiosk_container
    links:
      - "mongo:mongo"
    networks:
      - kiosk_backend
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    container_name: kiosk_db
    networks:
      - kiosk_backend
### Networks Setup ############################################
networks:
  kiosk_backend:
    driver: "bridge"
### Volumes Setup #############################################
volumes:
  web:
    driver: "local"

  
