version: '2'
services:
  kiosk:
    build: ./
    ports:
      - "81:80"
    volumes:
      - "../:/var/www/html/"
      # - "./data/:/var/log/"
    container_name: kiosk_container
    links:
      - "mongo:mongo"
    networks:
      - kiosk_backend
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "27018:27017"
    container_name: kiosk_db
    networks:
      - kiosk_backend
### Networks Setup ############################################
networks:
  kiosk_backend:
    driver: "bridge"
### Volumes Setup #############################################
volumes:
  web:
    driver: "local"

  
